# Generated by Django 4.1.1 on 2022-11-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=5)),
                ('member_name', models.CharField(max_length=255)),
                ('member_remark', models.CharField(max_length=255)),
            ],
        ),
    ]
