# Generated by Django 4.1.1 on 2022-11-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_test', '0002_table_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_members',
            name='member_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
