# Generated by Django 4.1.1 on 2022-11-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_test', '0003_alter_table_members_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_members',
            old_name='member_remark',
            new_name='member_surname',
        ),
    ]
