# Generated by Django 4.1.1 on 2022-11-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_test', '0005_table_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_login',
            name='remark_login',
            field=models.CharField(max_length=100),
        ),
    ]
